# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestions',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Question')),
                ('shuffle_answers', models.BooleanField(default=False)),
            ],
            bases=('courses.question',),
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Question')),
            ],
            bases=('courses.question',),
        ),
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='rating',
            field=models.IntegerField(default=b'12'),
        ),
    ]
