# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20161228_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Question'),
        ),
        migrations.AlterField(
            model_name='text',
            name='description',
            field=models.CharField(choices=[(b'badly_explained', b'Badly Explained'), (b'too_difficult', b'Too Difficult'), (b'bad_material', b'Bad Material')], max_length=26),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Question'),
        ),
    ]
